# TODO: 配置 Yarn 设置
# 1. 设置 node 链接器
# nodeLinker: node-modules

# 2. 配置镜像源
# npmRegistryServer: "https://registry.npmmirror.com"

# 3. 启用 PnP 模式
# nodeLinker: pnp

# 4. 配置工作空间
# enableGlobalCache: true